- Cargo.toml
- src/transport.rs
Looks like updating to tokio 1.0 is not that complicated. 
I have a bunch of tests failing but looks like its cause of my local setup. 
I am new to rust and tokio. So not very sure about this change.
```
failures:
---- frame::events::server_event::status_change_down stdout ----
thread 'frame::events::server_event::status_change_down' panicked at 'assertion failed: `(left == right)`
left: `"127.0.0.1:1"`,
right: `"V4(127.0.0.1:1)"`', src/frame/events.rs:554:17
---- frame::events::server_event::status_change_up stdout ----
thread 'frame::events::server_event::status_change_up' panicked at 'assertion failed: `(left == right)`
left: `"127.0.0.1:1"`,
right: `"V4(127.0.0.1:1)"`', src/frame/events.rs:535:17
---- frame::events::server_event::topology_change_new_node stdout ----
thread …
```
> Upgrading to tokio 1.0

- src/query/utils.rs
The `send_frame` function did use `write` method to send out
frame data. The method actually writes just a portion of the data provided
(usually first 16K). The rest was not written and got lost.
That caused Cassandra node peer send no reply waiting for more frame data,
which in turn led to `send_frame` hanging infinitely.
The `write_all` method has to be used instead.
> Fix query execution lock-up for large frames.

- src/cluster/generic_connection_pool.rs
- src/cluster/mod.rs
- src/cluster/pager.rs
- src/cluster/rustls_connection_pool.rs
- src/cluster/session.rs
- src/cluster/tcp_connection_pool.rs
- src/error.rs
- src/frame/parser.rs
- src/query/batch_executor.rs
- src/query/exec_executor.rs
- src/query/prepare_executor.rs
- src/query/query_executor.rs
- src/query/utils.rs
- src/transport.rs
This is a series of changes that improve the ability to control connection and session behaviour by users of this library. It does this by adding a new 'kind' of session configuration object that knows its own connection pool type and a function in the session module to initialize a session with it.
The use case for this, in my case, is an internal connection pooling mechanism and internal-specific requirements on TLS parameters. These things are also connected to each other and need to work in concert, so it's not enough to simply implement a new LoadBalancer. Note that it is currently at least very difficult, if not impossible, to implement and use a custom connection type or even load balancer from outside the cdrs_tokio codebase due to several traits not being exposed as pub, so even …
> Library improvements to extend connection and session behaviour by client users

- src/cluster/mod.rs
- src/cluster/session.rs
Per feedback on #11 
Also fixes the Error associated type constraint on ConnectionConfig to correctly use FromCDRSError.
> Rename generic connect method, add unstable dynamic version.

- src/cluster/pager.rs
- src/types/mod.rs
This makes some variables `pub` so I can send the bytes from a paging function to clients which they can send back to retrieve the next page.
Note: I did not expose the `bytes` variable but created a method `into_bytes` so the CBytes can never be created by a user. I don't like the `get_cursor` method on `PagerState` because that uses a `clone` which is unnecessary (in my case).
> Exposing variables

- examples/generic_connection.rs
- src/cluster/mod.rs
- src/cluster/session.rs
This adds a simple, fairly contrived, example of using the generic connection mechanism. This also came with a slight re-factor/re-naming from needs discovered later and from creating this example and wanting to make sure it was clear.
The example still uses the built in connection manager and transport, but changes what it connects to. I think even though it doesn't cover all available functionality it's a good starting point and is more concise than it would otherwise be.
> As requested, adding an example of the 'generic connection' mechanism

- cassandra-protocol/src/types.rs
Removes all instances of unsafe in the codebase:
* cursor_next_value implementation is invoking UB so I replaced it with the equivalent safe code:
+ As you can see in the `set_len` [safety section](https://doc.rust-lang.org/std/vec/struct.Vec.html#safety-2) the old implementation is breaking the invariant `The elements at old_len..new_len must be initialized.`
- We could possibly add a correct unsafe implementation in the future but I would expect benchmarks demonstrating a performance improvement before accepting it.
* The tests really have no reason to use unsafe, explicitly writing out the array works just as well.
> remove unsafe usage

- cassandra-protocol/src/frame/frame_result.rs
- cdrs-tokio/src/cluster/session.rs
- Merge `ks_name` and `table_name` in `ColSpec` to a struct called `TableSpec` since they will either be both present or both absent.
- Convert the tuples in `RowsMetadata` and `PreparedMetadata` to use the same struct. Using a struct instead of a tuple lets them be accessed with field names instead of indexes.
> Merge ks and table in ColSpec

- cassandra-protocol/src/frame/frame_query.rs
- cassandra-protocol/src/query/query_params.rs
- cassandra-protocol/src/query/query_params_builder.rs
- cdrs-tokio/src/cluster/connection_manager.rs
- changelog.md
By changing:
* with_names to be `bool` instead of `Option<bool>`
* removing the flags field (flags are now generated at serialization time)
we get a much better UX as many invalid states are no longer possible.
> Make invalid states unrepresentable in QueryParams

- cassandra-protocol/src/frame.rs
- cassandra-protocol/src/frame/frame_auth_challenge.rs
- cassandra-protocol/src/frame/frame_authenticate.rs
- cassandra-protocol/src/frame/frame_error.rs
- cassandra-protocol/src/frame/frame_response.rs
- cassandra-protocol/src/frame/frame_result.rs
- cassandra-protocol/src/frame/frame_supported.rs
- cassandra-protocol/src/types.rs
Adds test infrastructure that will be used for testing the encode and decode implementations which will come in follow up PRs.
For now just tests ResponseBody::Ready as that case already works.
> Add frame encode/decode round trip test

- cassandra-protocol/Cargo.toml
- cassandra-protocol/src/frame.rs
- cassandra-protocol/src/frame/frame_auth_response.rs
- cassandra-protocol/src/frame/frame_batch.rs
- cassandra-protocol/src/frame/frame_execute.rs
- cassandra-protocol/src/frame/frame_options.rs
- cassandra-protocol/src/frame/frame_prepare.rs
- cassandra-protocol/src/frame/frame_query.rs
- cassandra-protocol/src/frame/frame_register.rs
- cassandra-protocol/src/frame/frame_response.rs
- cassandra-protocol/src/frame/frame_result.rs
- cassandra-protocol/src/frame/frame_startup.rs
- cdrs-tokio/Cargo.toml
- cdrs-tokio/examples/generic_connection.rs
- cdrs-tokio/src/cluster.rs
- cdrs-tokio/src/cluster/cluster_metadata_manager.rs
- cdrs-tokio/src/cluster/config_rustls.rs
- cdrs-tokio/src/cluster/config_tcp.rs
- cdrs-tokio/src/cluster/connection_manager.rs
- cdrs-tokio/src/cluster/control_connection.rs
- cdrs-tokio/src/cluster/rustls_connection_manager.rs
- cdrs-tokio/src/cluster/session.rs
- cdrs-tokio/src/cluster/tcp_connection_manager.rs
- cdrs-tokio/src/frame_parser.rs
- cdrs-tokio/tests/collection_types.rs
- cdrs-tokio/tests/native_types.rs
The developer may wish to provide a configurable cassandra protocol version, this is impossible if the protocol is set at compile time.
* When deserializing a body the version comes from the frame.
* When serializing a frame I've tried to have the version come from a config struct in cdrs-tokio where possible but I think the API could be improved in the future.
> Move protocol version selection to runtime

- cassandra-protocol/src/consistency.rs
- cassandra-protocol/src/frame/frame_ready.rs
- cassandra-protocol/src/types.rs
- cassandra-protocol/src/types/decimal.rs
- cassandra-protocol/src/types/value.rs
Seems like this was left over from when `Serialize` used to be called `IntoCBytes`
> Rename into_cbytes tests

- cassandra-protocol/src/types/value.rs
- cdrs-tokio-helpers-derive/src/into_cdrs_value.rs
- cdrs-tokio/tests/tuple_types.rs
- cdrs-tokio/tests/user_defined_types.rs
- changelog.md
This makes the implementation and use of these types drastically simpler and removes an allocation when Null or NotSet.
> Improve Value type

- cassandra-protocol/src/frame.rs
- cassandra-protocol/src/frame/frame_query.rs
- cassandra-protocol/src/frame/frame_request.rs
- cassandra-protocol/src/frame/frame_response.rs
- cassandra-protocol/src/query/query_params.rs
- cassandra-protocol/src/types/value.rs
- cdrs-tokio/examples/crud_operations.rs
- cdrs-tokio/examples/generic_connection.rs
- cdrs-tokio/examples/insert_collection.rs
- cdrs-tokio/examples/multiple_thread.rs
- cdrs-tokio/src/cluster/cluster_metadata_manager.rs
- cdrs-tokio/src/cluster/connection_manager.rs
- cdrs-tokio/src/cluster/control_connection.rs
- cdrs-tokio/src/cluster/pager.rs
- cdrs-tokio/src/cluster/session.rs
- cdrs-tokio/src/frame_parser.rs
- cdrs-tokio/src/transport.rs
- cdrs-tokio/tests/collection_types.rs
- cdrs-tokio/tests/derive_traits.rs
- cdrs-tokio/tests/keyspace.rs
- cdrs-tokio/tests/native_types.rs
- cdrs-tokio/tests/query_values.rs
- cdrs-tokio/tests/topology_aware.rs
- cdrs-tokio/tests/tuple_types.rs
- cdrs-tokio/tests/user_defined_types.rs
* I had to add `test_encode_decode_roundtrip_nondeterministic` because of the hashmap in NamedValues
> query params decoding

- cassandra-protocol/src/error.rs
- cassandra-protocol/src/frame/events.rs
- cassandra-protocol/src/frame/frame_authenticate.rs
- cassandra-protocol/src/frame/frame_error.rs
- cassandra-protocol/src/frame/frame_register.rs
- cassandra-protocol/src/frame/frame_result.rs
- cassandra-protocol/src/frame/frame_startup.rs
- cassandra-protocol/src/frame/frame_supported.rs
- cassandra-protocol/src/frame/traits.rs
- cassandra-protocol/src/query/query_params.rs
- cassandra-protocol/src/query/query_values.rs
- cassandra-protocol/src/types.rs
- cassandra-protocol/src/types/data_serialization_types.rs
- cassandra-protocol/src/types/udt.rs
- cdrs-tokio/src/cluster/session.rs
- cdrs-tokio/src/transport.rs
This PR improves:
* cassandra-protocol UX - users can directly use String types without worrying about cassandra implementation details
* speed - removes many allocations
Future work:
We will also want to remove CStringLong and CStringList but this PR is already large enough.
> Remove CString

- cassandra-protocol/Cargo.toml
- cassandra-protocol/src/frame.rs
Printing `Frame` with `{:?}` dumps the entire body to the logs and makes them noisy.
> Ignore body in Frame debug formatting

- cdrs-tokio/src/cluster.rs
- cdrs-tokio/src/cluster/send_frame.rs
Allows lower-level use of `Session` e.g.
```Rust
let response: Result<Frame, cassandra_protocol::error::Error> = {
let mut query_params = QueryParamsBuilder::new().finalize();
let is_idempotent = query_params.is_idempotent;
let keyspace = query_params.keyspace.as_deref();
let token = query_params.token.take();
cdrs_tokio::cluster::send_frame::send_frame(
&self.session,
frame,
is_idempotent,
keyspace,
token,
None,
None,
)
.await
};
```
> Make send_frame public

- cassandra-protocol/src/frame.rs
- cassandra-protocol/src/frame/frame_auth_response.rs
- cassandra-protocol/src/frame/frame_batch.rs
- cassandra-protocol/src/frame/frame_execute.rs
- cassandra-protocol/src/frame/frame_options.rs
- cassandra-protocol/src/frame/frame_prepare.rs
- cassandra-protocol/src/frame/frame_query.rs
- cassandra-protocol/src/frame/frame_register.rs
- cassandra-protocol/src/frame/frame_startup.rs
- cdrs-tokio/src/frame_parser.rs
I happened to notice today that Vec does not allocate when constructed with capacity 0:
* https://doc.rust-lang.org/std/vec/struct.Vec.html#method.new
* https://doc.rust-lang.org/std/vec/struct.Vec.html#method.with_capacity
This means that `Vec::new()`, `vec![]` and `Vec::with_capacity(0)` will all cause no allocations.
Because of this wrapping the warnings in Option provides no benefit.
> Revert wrapping warnings in an Option

- cassandra-protocol/src/macros.rs
- cassandra-protocol/src/types.rs
- cassandra-protocol/src/types/cassandra_type.rs
- cassandra-protocol/src/types/data_serialization_types.rs
- cassandra-protocol/src/types/list.rs
- cassandra-protocol/src/types/map.rs
- cassandra-protocol/src/types/tuple.rs
- cassandra-protocol/src/types/udt.rs
- cassandra-protocol/src/types/value.rs
Adds the ability to parse a collection into usable types without knowing the type that the collection is supposed to be storing beforehand.
https://github.com/conorbros/shotover-proxy/blob/d51d063da82ade4828309e921848529892159cfc/shotover-proxy/src/message/mod.rs#L458
https://github.com/conorbros/shotover-proxy/blob/d51d063da82ade4828309e921848529892159cfc/shotover-proxy/src/message/mod.rs#L595
https://github.com/conorbros/shotover-proxy/blob/d51d063da82ade4828309e921848529892159cfc/shotover-proxy/src/message/mod.rs#L562
> Typed collections

- cassandra-protocol/src/types/cassandra_type.rs
BigInt should be an `I64` not a `num::BigInt` type. Fixing that mistake.
> fix CassandraType::BigInt

- cassandra-protocol/src/macros.rs
- cassandra-protocol/src/types.rs
- cassandra-protocol/src/types/cassandra_type.rs
- useful if you want to create `CassandraType`'s yourself
- All types are now convertible except for Custom.
> Export get_wrapper_fn and add functions for wrapping collections

- cassandra-protocol/src/macros.rs
- Fix some of the error messages
- Allow `Varint` to be converted into `num::BigInt`
> as_rust_type macro fixes

- cassandra-protocol/src/frame/frame_result.rs
In the unit test, the test bytes didn't have the `GLOBAL_TABLE_SPACE` flag set and had a columns count of 0, which meant that the parser wasn't attempting to read any more metadata so this bug wasn't exposed. 
I've updated the unit test to have a column count of 3 so that if the `NO_METADATA` flag wasn't set, it would be attempting to read further metadata.
> No metadata bug fix

- cassandra-protocol/src/types.rs
Both methods do the same thing so I have removed `into_plain` in favour of `into_bytes` as it is more descriptive to me. Happy to switch around though, or maybe just deprecate `into_plain` if we don't want to release a breaking change.
> remove into_plain in favour of into_bytes

- cassandra-protocol/src/frame/frame_startup.rs
- A `[string map]` in the Cassandra protocol has [a short specifying it's length](https://github.com/apache/cassandra/blob/8b15f8f22e8126f527ba0d39b9d13b20577c0192/doc/native_protocol_v4.spec#L261). I've modified the `from_cursor` method to read a short instead of an int.
- Add a test that exposes the bug that existed.
> Fix bug in BodyReqStartup::from_cursor

- cassandra-protocol/src/frame.rs
- cassandra-protocol/src/frame/frame_result.rs
Improves API by ensuring there is one source of truth.
> Cleanup prepared metadata

- cdrs-tokio/Cargo.toml
- cdrs-tokio/src/cluster/cluster_metadata_manager.rs
The `class` property obviously can't be parsed by `extract_replication_factor`. I fixed parsing, but it's still not type safe, maybe I make a few MR later.
> Configuration of replication strategy parsing fix.

- cassandra-protocol/src/frame/frame_batch.rs
- cassandra-protocol/src/query/batch_query_builder.rs
The is_prepared field is duplicating state from the subject field.
> Remove BatchQuery::is_prepared field

- cassandra-protocol/src/frame/frame_batch.rs
The warning only applies to the NamedValues variant of QueryValues.
I also left off the implementation details that the user doesnt need to know.
> Move docs on BatchQuery::values onto QueryValues::NamedValues

- cassandra-protocol/Cargo.toml
- cdrs-tokio/Cargo.toml
This is a breaking change because uuid types are exposed in the public API
> Update uuid to 1.0

- cassandra-protocol/src/frame.rs
We have a use case where we only want to check that the frame length and version are valid before fully parsing it.
> check_frame method

- cdrs-tokio/Cargo.toml
- cdrs-tokio/src/cluster/node_info.rs
The debug logs are very noisy if we include the tokens in the `NodeInfo` debug impl.
> make logs less noisy

- cdrs-tokio/src/cluster/cluster_metadata_manager.rs
There is only one `trace!` level log, so this might as well be `debug!` level.
> change trace to debug

- cassandra-protocol/src/frame/message_response.rs
Adding this because I needed it and we have methods for all the other result types so makes sense having one for error too.
> ResponseBody into error method

- cdrs-tokio/examples/multiple_thread.rs
Before it was awaiting for each iteration to be done, therefore not in parallel.
I changed it to be in parallel
> multithread example - wasn't in parallel

- cassandra-protocol/src/frame/events.rs
- cassandra-protocol/src/frame/message_error.rs
- cassandra-protocol/src/frame/message_event.rs
- cassandra-protocol/src/types.rs
- cdrs-tokio/src/cluster/cluster_metadata_manager.rs
Make the public API easier to use as the user does not need to know about the CInet implementation detail
> Remove CInet

- cassandra-protocol/src/frame/message_ready.rs
So it can be used in enums with the other message body structs.
> clone for BodyResReady

- cassandra-protocol/src/error.rs
- cassandra-protocol/src/frame/message_error.rs
- cdrs-tokio/src/cluster/cluster_metadata_manager.rs
- cdrs-tokio/src/cluster/session.rs
- cdrs-tokio/src/retry/retry_policy.rs
error_code can just be derived from the AdditionalErrorInfo at encode time.
> Make invalid states unrepresentable in ErrorBody

- cassandra-protocol/src/frame/message_query.rs
- cassandra-protocol/src/query.rs
- cdrs-tokio/src/cluster/cluster_metadata_manager.rs
- cdrs-tokio/src/cluster/session.rs
BodyReqQuery and Query have the exact same definition.
So I kept BodyReqQuery which is consistent with other such types and replaced all usages of Query with BodyReqQuery
> Replace query::Query with BodyReqQuery

- cdrs-tokio/src/cluster/session.rs
The length of the value should not be encoded in the routing key if it's a single partition key. 
The serialisation rules for composite partition keys include the length so that can remain. 
Notes:
https://github.com/apache/cassandra/blob/trunk/src/java/org/apache/cassandra/db/marshal/CompositeType.java
> don't include value length in serialised routing key

- cassandra-protocol/src/frame/message_result.rs
- cassandra-protocol/src/types/cassandra_type.rs
`ColType` is used to represent the type a field has.
A field cannot have a null type so I have removed the `Null` variant from `ColType`.
This is not to be confused with `CassandraType` where the `Null` variant is possible because it represents the returned results of a field which may be of the fields type or may be null.
> Remove ColType::Null

- cassandra-protocol/src/types.rs
- cassandra-protocol/src/types/data_serialization_types.rs
- cassandra-protocol/src/types/rows.rs
- cdrs-tokio/examples/paged_query.rs
The current method names of CBytes confuses the null and empty states.
The spec explains they are two separate states: https://github.com/apache/cassandra/blob/ee8b66da8ce3bdac0378f89159d8bd7e45a91363/doc/native_protocol_v5.spec#L1063
> CBytes properly distinguish between null and empty as per spec

- cassandra-protocol/Cargo.toml
- cassandra-protocol/src/token.rs
The position was not being updated properly and the loop while condition was incorrect. Using the bytes library means the bytes can be removed from the partition key as it loops.
> Murmur3 fix

- cdrs-tokio/Cargo.toml
- cdrs-tokio/examples/crud_operations.rs
- cdrs-tokio/examples/insert_collection.rs
- cdrs-tokio/examples/multiple_thread.rs
- cdrs-tokio/examples/paged_query.rs
- cdrs-tokio/examples/prepare_batch_execute.rs
- cdrs-tokio/src/cluster/control_connection.rs
- cdrs-tokio/src/cluster/session.rs
- cdrs-tokio/src/lib.rs
- cdrs-tokio/tests/common.rs
- cdrs-tokio/tests/compression.rs
- cdrs-tokio/tests/keyspace.rs
- cdrs-tokio/tests/multi_node_speculative_execution.rs
- cdrs-tokio/tests/multithread.rs
- cdrs-tokio/tests/paged_query.rs
- cdrs-tokio/tests/single_node_speculative_execution.rs
- cdrs-tokio/tests/topology_aware.rs
closes https://github.com/krojew/cdrs-tokio/issues/135
The Session::build method is now async.
The build method will not return until the control connection has completed its setup.
I believe this solves both of the issues noted in https://github.com/krojew/cdrs-tokio/issues/135
I had to change this:
```rust
impl<
T: CdrsTransport,
CM: ConnectionManager<T>,
LB: LoadBalancingStrategy<T, CM> + Send + Sync + 'static,
> SessionConfig<T, CM, LB>
```
to this: (note the added `'static`)
```rust
impl<
T: CdrsTransport + 'static,
CM: ConnectionManager<T> + 'static,
LB: LoadBalancingStrategy<T, CM> + Send + Sync + 'static,
> SessionConfig<T, CM, LB>
```
Not sure if this will have any affect on usability or not, my projects use of cdrs-tokio still compiles fine.
> Session::build is async and waits on task init

- cassandra-protocol/Cargo.toml
- cassandra-protocol/src/frame/traits.rs
- cassandra-protocol/src/types.rs
- cassandra-protocol/src/types/cassandra_type.rs
- cassandra-protocol/src/types/data_serialization_types.rs
- cassandra-protocol/src/types/decimal.rs
- cassandra-protocol/src/types/list.rs
- cassandra-protocol/src/types/map.rs
- cassandra-protocol/src/types/rows.rs
- cassandra-protocol/src/types/tuple.rs
- cassandra-protocol/src/types/udt.rs
- cassandra-protocol/src/types/value.rs
* arrayref is not needed, we can just create an array and convert that to the ip address.
* num is a meta crate that just reexports the crates that it uses. We can avoid a whole bunch of `num-*` subdependencies we dont need by just directly using num-bigint
+ this is not a breaking change since its actually the same type just accessed without the meta crate reexporting it.
* I removed "std" feature from time since time enables it by default anyway.
> Remove unneeded deps

- cdrs-tokio/src/cluster/cluster_metadata_manager.rs
- cdrs-tokio/src/cluster/connection_pool.rs
- cdrs-tokio/src/cluster/control_connection.rs
- cdrs-tokio/src/cluster/topology/node.rs
Issue description: https://github.com/krojew/cdrs-tokio/issues/198
Why this approach works:
- in control_connection.rs, when no nodes are available for load balancing, we fallback to configured URLs considering that all nodes in LB are dead anyway
- though, in `refresh_metadata()`, we work with them like they were still valid, which leads to the situations when we had only `Down` nodes in LB forever
- but if we call the `build_initial_metadata` method instead, we will not reuse nodes, all of which are down, and create fresh living instances instead
Tested locally a few times, but none of the files with changes has any unit tests to fix the behaviour
> Fixed the race condition happening during full TCP reconnection

- cdrs-tokio/Cargo.toml
- cdrs-tokio/src/cluster/session.rs
- cdrs-tokio/src/cluster/token_map.rs
- cdrs-tokio/src/load_balancing/topology_aware.rs
LazyLock was introduced in rust 1.80 from Aug 2024 and the latest release is rust 1.85
cdrs-tokio doesnt conform to any particular MSRV but 5 releases seems like a reasonable grace period.
All usages are equivalent but we now avoid the use of macros and avoid an extra dependency.
> Replace lazy_static crate with std library's LazyLock
